[package]
name = "nft"
version = "0.1.0"
authors = ["shiki.tak <shiki.tak@gmail.com>"]
edition = "2018"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces", "cosmwasm-vm/backtraces"]

[dependencies]
cosmwasm-std = { git = "https://github.com/line/cosmwasm", rev = "cbebb8a2f9666e820361413ce6652029f3bae9f7", features = ["iterator","staking","stargate"] }
cosmwasm-storage = {  git = "https://github.com/line/cosmwasm", rev = "cbebb8a2f9666e820361413ce6652029f3bae9f7", features = ["iterator"] }
schemars = "0.8.1"
bincode = "1.0"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = "1.0"
serde_json = "1.0"

[dev-dependencies]
cosmwasm-vm = { git = "https://github.com/line/cosmwasm", rev = "cbebb8a2f9666e820361413ce6652029f3bae9f7", default-features = false }
cosmwasm-schema = { git = "https://github.com/line/cosmwasm", rev = "cbebb8a2f9666e820361413ce6652029f3bae9f7" }
